'use strict';
const ACTOR_ID = 'apt';
const A = {
  name:'Nation-state / APT', sub:'Espionage & intelligence collection',
  colorClass:'theme-red', avClass:'av-cyan', init:'NS', catLabel:'Technical threat actor',
  tBase:97, sBase:52,
  cf:{age:.1,fin:.2,tech:.1,iso:.1,pub:.7,sm:.4,role:.95},
  ds:{ip:.95,id:.75,an:.85,mc:.80,wn:.90}, mdmW:.90, lw:{home:.10,usage:.85},
  na:['fin','tech'],
  bio:'State-sponsored groups operating under military or intelligence mandates with essentially unlimited budgets. Zero-click iOS exploit chains cost $1M–10M+ per target. This actor monitors silently for months, exfiltrating communications, contacts, location history, and documents. Primary targets include journalists, dissidents, diplomats, executives, and researchers with access to sensitive geopolitical, scientific, or corporate intelligence.',
  whyIdeal:'The APT hunts information and geopolitical leverage, not money. A foreign correspondent or defense contractor is worth far more than any billionaire who lacks professional access to sensitive intelligence.',
  ideal:[
    {key:'age',    l:'Age',             v:'35–60 — peak professional career'},
    {key:'fin',    l:'Financial status', v:'Not applicable — wealth is irrelevant to this actor'},
    {key:'tech',   l:'Tech skill',      v:'Not applicable — zero-click requires no user error'},
    {key:'iso',    l:'Social isolation', v:'Embedded in professional communities'},
    {key:'pub',    l:'Public profile',   v:'Moderate to very public — journalists, researchers'},
    {key:'sm',     l:'Social media',     v:'Active on LinkedIn and professional networks'},
    {key:'role',   l:'Job data',         v:'Government, executive, regulated, or sensitive research'},
    {key:'devices',l:'Devices',          v:'Any device used for professional communications'},
    {key:'loc',    l:'Location',         v:'International travel and surveillance-state border crossings'},
  ],
  match:{
    age:p=>p.age>=35&&p.age<=60, fin:()=>false, tech:()=>false,
    iso:p=>p.iso>=2&&p.iso<=3,   pub:p=>p.pub>=4, sm:p=>p.sm>=3,
    role:p=>p.role>=4,           devices:p=>p.ip||p.mc||p.wn, loc:p=>p.usage>=4,
  },
  tvecs:[
    {l:'Zero-click exploits (Pegasus/Triangulation-class)',v:99},
    {l:'Zero-day iOS kernel chain attacks',v:97},
    {l:'Baseband / radio layer attacks',v:90},
    {l:'Carrier-level lawful intercept abuse',v:88},
    {l:'Supply chain compromise',v:86},
    {l:'IMSI catcher / SS7 interception',v:84},
    {l:'Malicious MDM profile deployment',v:82},
    {l:'Compromised developer certificate abuse',v:78},
    {l:'DNS hijacking on enterprise networks',v:74},
    {l:'Physical forensics via specialized tools (Cellebrite)',v:70},
  ],
  svecs:[
    {l:'Spear-phishing (highly personalized)',v:78},
    {l:'Watering hole on frequented sites',v:72},
    {l:'Romance / honey trap operations',v:68},
    {l:'Human intelligence ops (HUMINT)',v:65},
    {l:'Fake job offer / recruiter approach',v:64},
    {l:'LinkedIn / social honeypot profiles',v:62},
    {l:'Compromised journalist contact',v:60},
    {l:'Conference / event social engineering',v:58},
    {l:'Trusted-contact compromise',v:55},
    {l:'Physical venue infiltration',v:52},
  ],
};
